version: "3"
services:
  recognizer:
    build:
      context: ./
    image: rokoucha/recognizer
  mysql:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: recognizer
      MYSQL_PASSWORD: recognizer
      MYSQL_ROOT_PASSWORD: recognizer-admin
      MYSQL_USER: recognizer
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
